name: BestSupplies
version: ${project.version}
main: dev.joshlucem.nullithstudios.bestsupplies.BestSupplies
api-version: '1.21'
description: Centro de Supplies - Diarias, banca mensual, raciones y pendientes
author: JoshLucem
website: https://github.com/JoshLucem/BestSupplies

depend:
  - Vault

softdepend:
  - LuckPerms
  - PlaceholderAPI
  - ItemsAdder

commands:
  supplies:
    description: Abre el menu principal de Supplies
    usage: /<command> [daily|bank|food|pending|admin]
    aliases: [suministros, abastecimiento]

permissions:
  bestsupplies.use:
    description: Permite usar /supplies
    default: true
  bestsupplies.daily:
    description: Permite acceder a recompensas diarias
    default: true
  bestsupplies.bank:
    description: Permite acceder a banca mensual
    default: true
  bestsupplies.food:
    description: Permite acceder a raciones
    default: true
  bestsupplies.pending:
    description: Permite acceder a pendientes
    default: true
  bestsupplies.admin:
    description: Acceso a comandos de administrador
    default: op

  bestsupplies.rank.default:
    description: Rango default
    default: false
  bestsupplies.rank.coal:
    description: Rango Coal
    default: false

  bestsupplies.rank.boost:
    description: Rango Boost
    default: false
  bestsupplies.rank.influencer:
    description: Rango Influencer
    default: false

  bestsupplies.rank.iron:
    description: Rango Iron
    default: false
  bestsupplies.rank.gold:
    description: Rango Gold
    default: false
  bestsupplies.rank.diamond:
    description: Rango Diamond
    default: false
  bestsupplies.rank.emerald:
    description: Rango Emerald
    default: false
  bestsupplies.rank.ruby:
    description: Rango Ruby
    default: false
  bestsupplies.rank.netherite:
    description: Rango Netherite
    default: false
